name: DeepUnit Workflow
description: The DeepUnit workflow generates a bug report and writes unit tests for every pull request that is opened.
branding:
  icon: 'award'  # Choose an icon from https://feathericons.com/
  color: 'purple'  # Use a hex code or a standard color name

on:
  workflow_dispatch:
    inputs:
      paths:
        description: 'Paths to test'
        required: true
      pr:
        description: 'Pull request ID'
        required: true

jobs:
  run-deepunit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run DeepUnit
        run: npx deepunit@latest --f ${{ github.event.inputs.paths }} --json --ff --email 'support@deepunit.ai' --meta ${{ github.event.inputs.pr }}

      - name: Store as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: deepunit-tests
          path: deepunit-tests.json
